### ISSUE TITLE
Using hm-graphql-auto-api-explorer behind a reverse proxy

### ISSUE THREAD

**Issue by SurinameClubcard** [highmobility/hm-graphql-auto-api-explorer#12]
This isn't an issue, nevertheless, I just wanted to mention that using this application when deployed behind a reverse proxy (like `haproxy` or `nginx`) requires the rewrite of the host header in the configuration of the reverse proxy, for connections towards the backend.

For `haproxy`: `http-request set-header Host "your.fixed.hostname"` (see https://www.haproxy.com/documentation/hapee/latest/traffic-routing/rewrites/rewrite-requests/#set-a-header)
For `nginx`: `proxy_set_header Host "your.fixed.hostname";` (see https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header)

You might want to add this to the README.md.

**Comment by kevinvaldek** [comment]
Thanks, noted in the README!
